language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean check

after_success:
  - ./gradlew reportScoverage coveralls